---
- name: Gather facts
  hosts: network

  tasks:
    - name: Gather Arista facts
      arista.eos.eos_facts:
        gather_subset: 
          - all
          - "!config"
      when: ansible_network_os == 'arista.eos.eos'

    - debug: var=ansible_facts

    # - name: Retrieve Junos OS version
    #   junipernetworks.junos.junos_command:
    #     commands: show version
    #   when: ansible_network_os == 'junipernetworks.junos.junos'
