---
- name: Test
  hosts: juniper
  # module_defaults:
  #   group/netbox.netbox.netbox:
  #     netbox_url: "{{ netbox.url }}"
  #     netbox_token: "{{ netbox.token }}"

  tasks:
    # - name: Arista - collect L2 interfaces data from devices
    #   arista.eos.eos_facts:
    #     gather_network_resources: 
    #       - "l2_interfaces"
    #     gather_subset:
    #       - min
    #   register: arista_l2_interfaces
    #   when: 
    #     - inventory_hostname in groups['switches']
    #     - inventory_hostname in groups['arista']

    # - debug: msg="{{ arista_l2_interfaces }}"

    # - name: run show version on remote devices
    #   junipernetworks.junos.junos_command:
    #     commands: show version
    #   register: showver

    # - debug: msg="{{ showver }}"

    # - name: Juniper - collect vlans from devices
    #   ansible.utils.cli_parse:
    #     command: show vlans
    #     parser:
    #       name: ansible.netcommon.ntc_templates
    #     set_fact: juniper_vlans

    # - debug: msg="{{ juniper_vlans }}"

    # - name: "Cisco - collect vlans from devices"
    #   ansible.utils.cli_parse:
    #     command: "show vlan"
    #     parser:
    #       name: ansible.netcommon.ntc_templates
    #     set_fact: cisco_vlans
    #   when:
    #     - inventory_hostname in groups['switches']
    #     - inventory_hostname in groups['cisco']