---
- name: Test
  hosts: arista
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox.url }}"
      netbox_token: "{{ netbox.token }}"

  tasks:
    - name: Arista - collect L2 interfaces data from devices
      arista.eos.eos_facts:
        gather_network_resources: 
          - "l2_interfaces"
        gather_subset:
          - min
      register: arista_l2_interfaces
      when: 
        - inventory_hostname in groups['switches']
        - inventory_hostname in groups['arista']

    - debug: msg="{{ arista_l2_interfaces }}"
 