---
- name: Test
  hosts: juniper
  # module_defaults:
  #   group/netbox.netbox.netbox:
  #     netbox_url: "{{ netbox.url }}"
  #     netbox_token: "{{ netbox.token }}"

  tasks:
    # - name: Arista - collect L2 interfaces data from devices
    #   arista.eos.eos_facts:
    #     gather_network_resources: 
    #       - "l2_interfaces"
    #     gather_subset:
    #       - min
    #   register: arista_l2_interfaces
    #   when: 
    #     - inventory_hostname in groups['switches']
    #     - inventory_hostname in groups['arista']

    # - debug: msg="{{ arista_l2_interfaces }}"

    # - name: run show version on remote devices
    #   junipernetworks.junos.junos_command:
    #     commands: show configuration interfaces 
    #     display: json
    #   register: show

    # - name: Juniper - collect vlans from devices
    #   ansible.utils.cli_parse:
    #     command: show ethernet-switching table
    #     parser:
    #       name: ansible.netcommon.ntc_templates
    #     set_fact: show

    # - debug: msg="{{ show }}"

    - name: "Run command and parse with textfsm"
      ansible.utils.cli_parse:
        command: show ethernet-switching table
        parser:
          name: ansible.utils.textfsm
          template_path: templates/juniper_junos_show_ethernet-switching_table.textfsm
        set_fact: show

    - debug: msg="{{ show }}"




    # - name: "Cisco - collect vlans from devices"
    #   ansible.utils.cli_parse:
    #     command: "show vlan"
    #     parser:
    #       name: ansible.netcommon.ntc_templates
    #     set_fact: cisco_vlans
    #   when:
    #     - inventory_hostname in groups['switches']
    #     - inventory_hostname in groups['cisco']

    # - name: Gather running vlans configuration
    #   junipernetworks.junos.junos_interfaces:
    #     state: gathered
    #   register: data

    # - debug: var=data

    # - name: collect interface configuration facts
    #   junipernetworks.junos.junos_facts:
    #     gather_subset: interfaces
    #     gather_network_resources:
    #       - interfaces
