---
- name: Test
  hosts: cisco, arista
  module_defaults:
    group/netbox.netbox.netbox:
      netbox_url: "{{ netbox.url }}"
      netbox_token: "{{ netbox.token }}"

  tasks:
    - name: "Cisco - collect interfaces data from devices"
      ansible.utils.cli_parse:
        command: "show interfaces"
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: cisco_interfaces
      when:
        - inventory_hostname in groups['cisco']

    - debug: msg="{{ cisco_interfaces }}"

    # - name: run show version command
    #   ansible.netcommon.cli_command:
    #     command: show version

  # roles:
  #   - gather_network_facts  
    # - add_devices_configuration_to netbox

