---
- name: Gather Cisco facts
  cisco.ios.ios_facts:
    gather_subset: 
      - all
      - "!config"
  when: ansible_network_os == 'cisco.ios.ios'

- name: Gather Arista facts
  arista.eos.eos_facts:
    gather_subset: 
      - all
      - "!config"
  when: ansible_network_os == 'arista.eos.eos'

- name: Gather Juniper data
  ansible.utils.cli_parse:
    command: "show version"
    parser:
      name: ansible.netcommon.ntc_templates
    set_fact: juniper_sh_ver