---
- name: Add Devices to NetBox
  netbox.netbox.netbox_device:
    data: 
      name: "{{ inventory_hostname }}"
      site: "{{ site }}"
      device_type: "{{ type }}"
      device_role: "{{ role }}"
      comments: "added by Ansible"
