---
# Different ways of collecting data from network devices are shown here (ansible facts and ntc-templates)
# Interfaces and IP addresses are added using gathered ansible facts
# - name: Cisco - add interfaces
#   netbox.netbox.netbox_device_interface:
#     data:
#       device: "{{ inventory_hostname }}"
#       name: "{{ item.key }}"
#       type: "Virtual"
#       description: "{{ item.value.description }}"
#       mac_address: "{{ item.value.macaddress }}"
#       mtu: "{{ item.value.mtu }}"
#     state: present
#   with_dict:
#     - "{{ ansible_net_interfaces }}"
#   when: ansible_network_os == 'cisco.ios.ios'

# - name: Cisco - add IP addresses to interfaces
#   netbox.netbox.netbox_ip_address:
#     data:
#       address: "{{ item.value.ipv4 | map(attribute='address') | join() ~ '/' ~ item.value.ipv4 | map(attribute='subnet') | join() }}"
#       assigned_object:
#         name: "{{ item.key }}"
#         device: "{{ inventory_hostname }}"
#     state: present
#   with_dict:
#     - "{{ ansible_net_interfaces }}"
#   when: 
#     - ansible_network_os == 'cisco.ios.ios'
#     - item.value.ipv4 | map(attribute='address')

# - name: Arista - add interfaces
#   netbox.netbox.netbox_device_interface:
#     data:
#       device: "{{ inventory_hostname }}"
#       name: "{{ item.key }}"
#       type: "Virtual"
#       description: "{{ item.value.description }}"
#       mac_address: "{{ item.value.macaddress }}"
#       mtu: "{{ item.value.mtu }}"
#     state: present
#   with_dict:
#     - "{{ ansible_net_interfaces }}"
#   when: ansible_network_os == 'arista.eos.eos'

# - name: Arista - add IP addresses to interfaces
#   netbox.netbox.netbox_ip_address:
#     data:
#       address: "{{ item.value.ipv4.address ~ '/' ~ item.value.ipv4.masklen }}"
#       assigned_object:
#         name: "{{ item.key }}"
#         device: "{{ inventory_hostname }}"
#     state: present
#   with_dict:
#     - "{{ ansible_net_interfaces }}"
#   when: 
#     - ansible_network_os == 'arista.eos.eos'
#     - item.value.ipv4.address is defined
